name: Build MacOs Bundle

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run:  |
        brew update --quiet
        brew install qt5 uchardet
        brew install faac flac lame  mp3gain  sox vorbisgain wavpack opus-tools
        cp -f /usr/local/bin/flac /usr/local/bin/mac
        cp -f /usr/local/bin/flac /usr/local/bin/ttaenc


    - name: Install Saprkle
      run: |
        curl -s -L https://github.com/sparkle-project/Sparkle/releases/download/1.26.0/Sparkle-1.26.0.tar.xz > Sparkle.tar.xz
        tar xf Sparkle.tar.xz Sparkle.framework

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Run CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake \
          -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 \
          -DBUILD_TESTS=No \
          -DMAC_BUNDLE=Yes \
          -DCMAKE_INSTALL_PREFIX=${CUR_DIR} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET="10.10.1" \
          -DCMAKE_FRAMEWORK_PATH=$GITHUB_WORKSPACE \
          -DFLACON_THIRD_PARTY_PATH="/usr/local/bin" \
          $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j 8

